version: '3'
services:
  main:
    container_name: main
    build: .
    volumes:
      - artifact:/home/dz1/boxfuse-sample-java-war-hello/target:rw
    
  web:
    container_name: web
    image: tomcat
    volumes:
      - artifact:/usr/local/tomcat/webapps:rw
    ports:
      - "8080:8080"

volumes:
  artifact:
